// The Field Manual's text.
//
// This lives apart from scenes_manual.cpp, and deliberately includes no SDL
// headers, so the headless test suite can check the page layout: the manual is
// authored against a fixed-width viewport, and a line that exceeds it wraps
// mid-sentence.
//
// Keep every line at or below maxTextCols(kManualViewportPx) columns. Run
// tools/reflow_manual.py after editing prose; it re-wraps paragraphs to the
// viewport while leaving tables and column-aligned listings alone.

#include "game/manual.h"

#include <algorithm>
#include <cstring>

namespace lt {

namespace {

const std::vector<ManualPage>& manualPages() {    static const std::vector<ManualPage> pages = {

{"LUNAR TRAIL  -  FIELD MANUAL", {
"Welcome aboard.",
"",
"You are the flight leader of a five-person surface",
"  convoy that has just set down on the lunar south",
"  pole. One hundred and twenty kilometres of",
"  broken ground lie between you and the site where",
"  two hundred people are waiting to find out",
"  whether you made it.",
"",
"You have water, oxygen, power, and propellant. You",
"  do not have enough of any of them. That is not a",
"  bug in the simulation; it is the job.",
"",
"Most convoys do not arrive. The ones that do are",
"  not lucky. They planned.",
}},

{"HOW TO USE THIS MANUAL", {
"Main menu -> Learn About The Trail.",
"",
"Left and Right pages through sections. Up and Down",
"  scrolls within a section. Escape returns to the",
"  main menu at any point.",
"",
"Sections are ordered the way you will meet them.",
"  If you only read three, read THE ECONOMY, THE",
"  SHADOW LINE, and HOW TO DIE.",
"",
"Everything stated here is exact. The numbers in",
"  this manual are the numbers the simulation uses.",
}},

{"1.  MISSION OVERVIEW", {
"The mission has two chapters.",
"",
"CHAPTER ONE - DESCENT",
"  Build the ascent stack in low Earth orbit, catch",
"    a trans-lunar injection window, insert into",
"    lunar orbit, and fly a powered descent onto",
"    the south pole rim. What you spend in orbit is",
"    what you arrive on the surface with. Most",
"    missions end here.",
"",
"CHAPTER TWO - THE TRAIL",
"  Drive one hundred and twenty kilometres to the",
"    colony site. Solve water, oxygen, power and",
"    propellant every single sol. Arrive with",
"    enough cargo to actually seed a colony.",
"",
"Win condition: reach the colony site with at least",
"  one surviving crew member and at least fifty",
"  kilograms of delivered colony cargo.",
"",
"Lose condition: no crew, no traction, no power in",
"  the dark, or you miss the crew rotation window.",
}},

{"2.  CHAPTER ONE:  THE MANIFEST", {
"You choose three things before launch.",
"",
"PROFESSION. Three tiers, and they are difficulty",
"  levels, not flavour. This is deliberate, and it",
"  is how the original worked: three professions,",
"  three budgets, three score multipliers.",
"",
"  Flight Director     16,000 credits     score x1",
"  Mission Specialist    8,800 credits     score x2",
"  Payload Technician    5,800 credits     score x3",
"",
"Credits are your entire economy. There is no way",
"  to earn them. They never come back. Spending",
"  them well is the whole of Chapter One.",
"",
"The Payload Technician is genuinely unable to buy",
"  enough propellant for the route and must mine",
"  most of it. That is the point of the tier,",
"  exactly as the original's Farmer was unable to",
"  buy enough food and had to hunt.",
"",
"CREW. Five named crew, each carrying one",
"  specialty. Specialties are survivors, not stat",
"  boosts. A Comms Officer who dies takes your",
"  route forecast with them.",
"",
"ROUTE SEED. The seed fixes every random roll for",
"  the entire run: every hazard, every repair,",
"  every crossing outcome. Write it down or retype",
"  it. Replaying a seed reproduces the route",
"  exactly, which is how you learn it.",
}},

{"3.  CHAPTER ONE:  THE LEO DEPOT", {
"You arrive in low Earth orbit with a fixed wet",
"  mass and an empty budget.",
"",
"Every kilogram you buy is a kilogram of",
"  propellant. Propellant is what gets you to the",
"  Moon and down to the surface. Propellant is",
"  also, indirectly, most of what you will have",
"  when you land, because mass you spend getting",
"  there is mass you do not have once you arrive.",
"",
"REFUEL WINDOWS. Three of them. Prices escalate",
"  sharply on the last, and the last one closes.",
"  Missing every window costs you the mission, not",
"  a penalty.",
"",
"Reserve LOX. Some oxidiser must survive the",
"  descent. If you buy down to zero you will reach",
"  the Moon and have nothing to land with.",
"",
"The depot's own warning, which is sound advice:",
"  \"Propellant is the only thing you cannot make",
"    on the way. Make sure you have enough before",
"    you leave the depot.\"",
}},

{"4.  CHAPTER ONE:  TLI, CRUISE, LLOI", {
"TRANS-LUNAR INJECTION. The window opens on sol 3",
"  and closes on sol 5. Burn inside the window or",
"  wait for the next one, which costs you sols you",
"  cannot spare. The burn is a mass-budget",
"  question, not a skill question: you either have",
"  the propellant for it or you do not.",
"",
"CISLUNAR CRUISE. Four days. Nothing to decide. The",
"  crew talk, the telemetry scrolls, and the mass",
"  readout is your last chance to see a number you",
"  will wish you had watched more closely.",
"",
"LUNAR ORBIT INSERTION. Capture into a 100 x 100 km",
"  near-polar orbit. Costs propellant and credits.",
"  Skipping it means a longer, more expensive",
"  descent.",
}},

{"5.  CHAPTER ONE:  POWERED DESCENT", {
"From fifteen kilometres up and seventeen hundred",
"  metres per second, with no atmosphere and",
"  therefore no drag and no visual cue to tell you",
"  how fast you are really going.",
"",
"CONTROLS",
"  UP / W throttle up (more thrust, less descent",
"    time)",
"  DOWN / S      throttle down",
"  LEFT / A      tilt left    RIGHT / D  tilt right",
"  SPACE         throttle to zero",
"",
"WHAT KILLS YOU",
"  Touchdown faster than 3 m/s vertical. You land",
"    like a dropped anvil. Still moving faster than",
"    2 m/s horizontally. You dig a trench and keep",
"    going.",
"  On a slope steeper than 15 degrees. A lander on",
"    a steep slope tips over,",
"    and at one sixth gravity that takes a very",
"      long time.",
"  Out of propellant above the surface. This is the",
"    classic lunar death and it",
"    is entirely your arithmetic.",
"",
"WHAT YOU CANNOT DO",
"  There is no drag, so slowing down is all you.",
"    There is no atmosphere to cue the flare. Read",
"    the vertical speed number, not your gut.",
"",
"A rough but survivable landing costs you cargo. A",
"  bad landing costs you the landing. Your entire",
"  Chapter One budget is being spent in the last",
"  four minutes of it.",
}},

{"6.  CHAPTER TWO:  THE DAILY LOOP", {
"Between landmarks the convoy autopilots. One sol",
"  passes about every second and a half. You can",
"  pause at any time; the game pauses itself on",
"  anything major.",
"",
"Order of operations each sol, which matters:",
"  1. collect solar",
"  2. spend power on life support and drive",
"  3. roll for malady",
"  4. consume food, water, oxygen",
"  5. roll a hazard",
"  6. compute distance",
"  7. advance the calendar",
"",
"The sequence is why a sol where you are about to",
"  run dry can still kill somebody first, and why",
"  your distance is computed from the resources you",
"  actually had rather than the ones you were about",
"  to lose.",
"",
"PACE",
"  Cruise      3 km/sol   electric. Sustainable.",
"  Sprint 6 km/sol electric, heavy. Wears the drive",
"    gear.",
"  Full Burn 14 km/sol chemical. Eats propellant",
"    and battery both.",
"",
"Full Burn is the only pace that reliably beats the",
"  shadow line, and it is also the fastest route to",
"  Critical health. That trade is the game.",
"",
"RATIONS",
"  Full Rations       1.00x   no health cost",
"  Reduced Rations    0.60x   steady health damage",
"  Emergency Rations  0.25x   serious health damage",
}},

{"7.  THE ECONOMY", {
"This is the most important page in the manual.",
"",
"Per crew member, per sol, you consume:",
"  Food          1.4 kg",
"  Water         3.5 L",
"  Oxygen       0.55 kg",
"  Energy      19.0 kWh",
"  Suit sets   0.03",
"",
"For five crew that is 27.25 kg and 95 kWh every",
"  sol. Across a typical seventy-two sol run that",
"  is 1,962 kg of consumables.",
"",
"Your total payload capacity is 2,100 kg.",
"",
"So the consumables alone fit, with about 140 kg to",
"  spare -- and that slack is exactly what",
"  propellant, spares and colony cargo have to fit",
"  into. They do not. That gap is why you must",
"  mine.",
"",
"Therefore: you must mine. Roughly four to eight",
"  sols of a seventy-two sol run will be spent at",
"  an ice face with a drill. Budget for that the",
"  way the original's players budgeted thirty to",
"  eighty days for hunting.",
}},

{"8.  IN-SITU RESOURCE USE", {
"Ice is water. Water is the whole economy.",
"",
"  Electrolysis    2 H2O  ->  2 H2 + O2",
"    1 kg water gives 0.111 kg oxygen, 0.889 kg",
"      hydrogen",
"",
"  Sabatier        CO2 + 4 H2  ->  CH4 + 2 H2O",
"    carbon dioxide comes from processed regolith,",
"      and is free",
"",
"  Stoichiometry   1 kg CH4 needs 0.333 kg H2",
"                  1 kg O2  needs 9.0 kg water",
"",
"  Total roughly 8 kg of ice per kg of usable",
"    propellant",
"",
"A sortie splits 55% as drinking water and 45%",
"  through electrolysis, so a 90 kg haul in the",
"  shadowed regions yields about 50 L of water, 4.5",
"  kg of oxygen, and 9 kg of LCH4.",
"",
"TWO CONSEQUENCES YOU SHOULD ACT ON",
"",
"  FUEL IS CHEAP. OXIDISER IS NOT. Making LCH4 on",
"    the Moon costs about four kilograms of ice per",
"    kilogram of fuel. Making LOX costs nine.",
"    Propellant made on the Moon is also much less",
"    efficient per kilogram than propellant made in",
"    a factory on Earth. So: BUY OXIDISER, MAKE",
"    YOUR OWN FUEL, MINE WATER FOR BREATHING.",
"    Anything else is a more expensive way of doing",
"    the same thing.",
"",
"  OXYGEN IS THREE JOBS. Every kilogram of oxygen",
"    in your tanks is either 0.20 sols of five",
"    crew's breathing, or propellant for a chemical",
"    burn, or neither. There is no third option and",
"    no way around it.",
"",
"OXYGEN MIXTURE LOCK",
"  Burning fuel with no oxidiser ignites nothing.",
"    If your fuel and oxidiser tanks fall out of",
"    the 1:6 ratio, you are carrying dead weight,",
"    you burn propellant per kilometre at a",
"    penalty, and you will eventually run out of",
"    one of them while the other is still full.",
"    Watch both bars, not one.",
}},

{"9.  PROSPECTING", {
"Prospecting is hunting. It is the hunting minigame",
"  with a drill.",
"",
"  One sortie costs one sol and returns at most 90",
"    kg of ice.",
"",
"That cap is the single most important rule in the",
"  prospecting system, and it is preserved",
"  deliberately from the original, which imposed a",
"  100 lb carry limit on hunting for exactly the",
"  same reason: so that the player learns to think",
"  about wastefulness. You can mine far more than",
"  you can carry.",
"",
"Yield depends on the zone you are standing in and",
"  on your crew:",
"  Sunlit Rim 0 kg per crew full sun, no ice",
"  Transition Slope  16 kg per crew",
"  Shadowed Region 52 kg per crew no sun, all the",
"    ice",
"",
"A Geologist raises every figure by 40 percent.",
"  That perk is worth more than it looks, because",
"  prospecting is where the run is decided.",
"",
"Each sortie also spends the consumables of the day",
"  it happens on. Prospecting is not free; it is a",
"  day of oxygen.",
}},

{"10.  ZONES AND THE SHADOW LINE", {
"The route crosses three lighting zones, and they",
"  are opposites.",
"",
"  SUNLIT RIM          220 kWh/sol    0 kg ice",
"  TRANSITION SLOPE 130 kWh/sol 16 kg ice per crew",
"  SHADOWED REGION 0 kWh/sol 52 kg ice per crew",
"",
"Energy and propellant are anti-correlated by",
"  geography. The sunlit rim makes far more power",
"  than you need and has no ice at all, so",
"  everything you burn must be carried in. The",
"  shadowed regions have the ice and make no power",
"  whatever, so everything you burn must be carried",
"  in too. The transition slope is break-even at",
"  Cruise and costs you charge at anything faster.",
"  No zone gives you both.",
"",
"THE SHADOW LINE A cruising five-person convoy",
"  draws 123 kWh a sol: 95 for life support and 28",
"  for the drive. Sprint draws 147. Full Burn draws",
"  180.",
"",
"Batteries hold 900 kWh, which is about seven sols",
"  in the dark. In a shadowed region solar is",
"  exactly zero. If you enter one on a full battery",
"  you have seven sols. If you enter one on half a",
"  battery you have three and a half.",
"",
"Route through the sunlit rim to recharge. A manned",
"  relay depot will charge you free, but it costs",
"  you two sols parked on the pad -- and near the",
"  shadow line, sols are the only thing you cannot",
"  make more of.",
"",
"The route does not respect the sun. Past sol 110",
"  the next crew rotation window closes and nobody",
"  is coming for you. This is the lunar answer to",
"  the original's blizzard in the mountains, and it",
"  is a wall, not a slope.",
}},

{"11.  HAZARDS", {
"Twenty-three things can go wrong. Probability is",
"  never flat: it is weighted by where you are and",
"  what you are doing. A boulder field does nothing",
"  in a shadowed region. Battery thermal runaway is",
"  far likelier after ten sols of Full Burn.",
"",
"There is no combat. Nothing can be fought, chased,",
"  or outrun. There are no hostile riders. Every",
"  hazard is something you could only have prepared",
"  for.",
"",
"THE HARDEST RULE IN THE GAME",
"  If a crew member is already suffering from a",
"    malady and suffers another, they die.",
"    Immediately.",
"",
"Ailments and diseases take ten sols to clear.",
"  Injuries take thirty. So the natural instinct to",
"  push through is exactly the wrong instinct: push",
"  through and the second thing that happens is a",
"  death.",
"",
"  Physician one second malady is survivable. Once.",
"  Resting the only reliable healing, because",
"    hazards do not fire while",
"    the convoy is stationary. This is a real and",
"      known exploit.",
"  Hazards      do not fire while resting, at all.",
"",
"",
"THE MERCY VALVE If food, water, oxygen or charge",
"  hits zero, there is roughly a one-in-three",
"  chance each sol that somebody flags a salvage",
"  cache you did not know about. It is the only",
"  free help in the game, it fires only from a",
"  standing start, and it is deliberately too late",
"  to rely on.",
}},

{"12.  CHASM CROSSINGS", {
"Five crossings. Two have a guided crossing",
"  available; three do not, and must be solved with",
"  your own equipment. This is the original's river",
"  structure, including the detail that at least",
"  two of the four are always a gamble.",
"",
"  RAMP TRAVERSE",
"    Free and immediate. Shallow crossings are",
"      nearly safe. Between the marginal depths you",
"      bog down and lose one sol jacking free,",
"      losing nothing else. Deeper than that, risk",
"      climbs linearly with depth and a failure is",
"      expensive.",
"",
"  GRAPPLE AND WINCH",
"    One sol, forty kWh, two cutting charges. Risk",
"      scales with span.",
"",
"  HOP ASSIST",
"    Not in the original. Burns across on the",
"      descent engine. Costs propellant and does",
"      not care about your wheels.",
"",
"  GUIDED CROSSING",
"    240 credits, lowest risk. May wait several",
"      sols for a support window.",
"",
"  LOCAL GUIDE",
"    Three suit sets. Cuts risk by 80 percent, and",
"      reduces losses too. The guide picks the line",
"      and the timing for you, never waits, and",
"      will not warn you about the current. The",
"      original's guide behaved the same way and it",
"      was infuriating there too.",
}},

{"13.  OUTPOSTS AND PRICES", {
"Five depots with stores, plus the landing depot.",
"",
"  Shackleton Rim Depot x1.00 what everything else",
"    is measured against",
"  Relay Post Krill       x1.25",
"  Relay Post Shoemaker   x1.50",
"  Relay Post Amundsen    x1.75",
"  Relay Post Gerlache    x2.00",
"",
"Exactly twenty-five percent per outpost,",
"  compounding nowhere. Every sol you delay is",
"  twenty-five percent more of everything, forever,",
"  for the rest of the route. Restock early and",
"  often even though it costs more per unit; the",
"  markup is the only part that scales.",
"",
"OUTPOSTS SELL food, water, oxygen, fuel, oxidiser,",
"  MMOD suit sets,",
"    cutting charges, spare traction units, spare",
"      drive bogies, spare seal kits, and colony",
"      cargo.",
"OUTPOSTS WILL NOT sell you traction units, drive",
"  bogies or seal kits beyond",
"    three of each. That limit is preserved from",
"      the original's three wheels, three axles,",
"      three tongues.",
"",
"SELLING BACK An outpost buys at depot price. You",
"  lose the markup, so selling",
"    is never the right answer to a cash problem.",
"BARTER Available between landmarks for one sol.",
"  Somebody proposes a swap;",
"    there is no haggling and credits are never on",
"      the table. Offers are value-neutral at best",
"      and usually favour them.",
}},

{"14.  CREW AND SPECIALTIES", {
"Five named crew. Specialties are not stat bonuses;",
"  they change rules.",
"",
"  Physician A second malady is survivable. Once.",
"    They cannot save the",
"                 same person twice.",
"  Geologist Prospecting yields 40 percent more",
"    ice. The single most",
"    valuable perk, because prospecting decides",
"      runs.",
"  Engineer Repairs almost always succeed instead",
"    of sometimes.",
"  Mechanic Hardware failures happen half as often.",
"  Comms Officer Reveals the route seed and an",
"    eight-sol hazard forecast.",
"    Without one you are gambling every sol.",
"",
"ANY CREW THAT DIES LOSES ITS SPECIALTY",
"  IMMEDIATELY.",
"",
"The default manifest is one of each. You may swap,",
"  but understand that the difficulty in this game",
"  comes from the economy, not from drawing a bad",
"  crew.",
}},

{"15.  HEALTH AND MALADIES", {
"Health is a single value from 0 to 140. Zero is",
"  perfect. 140 is death.",
"",
"  0 -  34    Nominal",
"  35 -  69    Degraded",
"  70 - 104    Stressed",
" 105 - 139    Critical",
"    140       Failing",
"",
"Each sol, in this exact order:",
"  health = health x 0.90 + (every modifier for the",
"    day)",
"",
"The recovery is applied BEFORE the modifiers, and",
"  that ordering is not cosmetic. It is why a party",
"  at 139 lands at 125 rather than dying instantly,",
"  and it is where the original's 'they die within",
"  a few days' window comes from.",
"",
"MODIFIERS INCLUDE pace, rations, thermal load,",
"  each maladied crew member,",
"    and shortages. A zero on oxygen is worth 30",
"      health a sol, water 14, food 9, and a dead",
"      battery 22.",
"",
"MALADIES Exhaustion, hypobaric hypoxia, oxygen",
"  toxicity, decompression",
"    sickness, dust pneumoconiosis. Ten sols.",
"INJURIES Fracture, sprain, crush injury, suit",
"  puncture. Thirty sols.",
}},

{"16.  SCORING", {
"Points, before your profession multiplier:",
"",
"  per surviving crew member",
"      500 Nominal   400 Degraded",
"      300 Stressed  200 Critical",
"  colony cargo delivered   1 per 10 kg",
"  spare traction unit      60 each",
"  spare drive bogie       120 each",
"  spare seal kit           48 each",
"  MMOD suit set            12 each",
"  credits held             1 per 5",
"",
"  RANKS   500+ Trainee    1500+ Expeditionary",
"         3000+ Trailblazer   5000+ Colony Founder",
"",
"THEN multiply by your profession: x1, x2 or x3.",
"",
"Note the deliberate property: five credits is one",
"  point whether you spend it or hold it, and",
"  converting five credits into any good is worth",
"  exactly one point. That is why restocking early",
"  is not merely advisable but correct, and why",
"  the spares above are priced rather than",
"  assigned: a drive bogie is worth double a",
"  traction unit because it costs double.",
}},

{"17.  SCOUTING", {
"SCOUTING THE WRECKS Every convoy that dies writes",
"  a record to your save file: crew name, distance",
"  reached, sol, profession, seed, and an epitaph",
"  if you write one. Those records persist across",
"  every future run, and they appear on your route",
"  map as crosses.",
"",
"Wrecks are not only gravestones. Stop at one and",
"  you may salvage suit sets and consumables from",
"  it. Somebody else's dead convoy is a resupply",
"  point.",
"",
"Your own failures become the next player's",
"  supplies. This was the original's most-loved",
"  feature and it is load-bearing here too.",
"",
"THE TOP TEN Every successful arrival is submitted.",
"  The board starts seeded with the explorers of",
"  the heroic age of Antarctic polar travel,",
"  spanning the plausible range, so a mediocre run",
"  has somewhere to sit.",
"",
"SEEDS Every run displays its seed. Entering the",
"  same seed with the same profession reproduces",
"  the route exactly. Learning the route is the",
"  intended way to win, and it is only possible",
"  because the seed is visible.",
}},

{"18.  HOW TO DIE", {
"Nine ways, and you should know all of them.",
"",
"  OXYGEN AT ZERO 30 health a sol. You have about",
"    an hour to notice.",
"  WATER AT ZERO        14 health a sol. Two sols.",
"  FOOD AT ZERO 9 health a sol. Three or four sols,",
"    if nothing else",
"                        goes wrong first.",
"  BATTERIES FLAT 22 health a sol in the dark, and",
"    no recharge to save",
"                        you.",
"  SECOND MALADY Instant. No warning, no roll, no",
"    saving throw.",
"  CHASMA FAILURE Possible to lose the entire rig",
"    and everyone not in",
"                        the cab.",
"  IMPASSABLE SLOPE Costs two sols, charge, and",
"    cargo to get around. Not",
"    fatal itself, but it will finish a starving",
"      convoy.",
"  HARD SOL LIMIT Sol 110. The rotation window",
"    closes.",
"  NO TRACTION No usable wheels. The convoy is a",
"    monument.",
"",
"AND THE ONE THAT CATCHES EVERYONE",
"  Buying everything at the last outpost, then",
"    discovering what the last four outposts were",
"    charging.",
}},

{"19.  CONTROLS", {
"GENERAL",
"  Arrow keys / WASD    Navigate menus",
"  Mouse                Click menus and buttons",
"  Enter / Space        Confirm",
"  Escape               Back one level",
"  F11                  Toggle fullscreen",
"  M                    Toggle sound",
"",
"TRAIL SCREEN",
"  RETURN Pause and open the action menu",
"  Up / Down Select a pace or ration level directly",
"  R Set Full Burn (hold SHIFT for Cruise)",
"",
"TEXT ENTRY",
"  Type to enter. CTRL-V pastes. Escape leaves the",
"    field.",
}},

{"20.  SURVIVAL ADVICE", {
"Ten things that will save your run.",
"",
"  1. Leave with six traction units. Fewer costs",
"    you speed, and speed is",
"     sols, and sols are everything.",
"  2. Take three of every spare. It is the cheapest",
"    insurance in the game. 3. Buy oxygen and water",
"    at Shackleton. They only get more expensive.",
"    4. Carry both fuel AND oxidiser in the right",
"    ratio. A full tank of one and",
"    an empty tank of the other is a waste of your",
"      payload cap.",
"  5. Enter shadowed regions with full batteries.",
"    You have about seven. 6. Prospect on the way",
"    in, not on the way out. Ice backtracks badly.",
"    7. Stop and rest when someone is maladied.",
"    Hazards do not fire while",
"    stationary. Resting is the only real medicine.",
"  8. Save your medic. A dead Physician converts a",
"    bad sol into a death. 9. Take a Comms Officer.",
"    Flying blind is not difficulty, it is",
"    gambling.",
" 10. Write down the seed. The route is learnable,",
"   and learning it is the",
"     entire skill of the game.",
"",
"Good luck. Most of them need it.",
}},

    };
    return pages;
}

}  // namespace

const std::vector<ManualPage>& manualPageTable() {
    return manualPages();
}

int manualWidestTextColumn() {
    int widest = 0;
    for (const ManualPage& p : manualPages()) {
        widest = std::max(widest, static_cast<int>(std::strlen(p.title)));
        for (const char* line : p.body) {
            widest = std::max(widest, static_cast<int>(std::strlen(line)));
        }
    }
    return widest;
}

}  // namespace lt
